[package]
name = "custom-hash"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
md-5 = "0.10.5"
sha2 = "0.10.6"
rayon = "1.5.3"
rustc-serialize = "0.3.24"
itertools = "0.10.5"
